trigger: none
parameters:
- name: parm_user
  displayName: Email Solicitante
  type: string
  default: ' '
- name: parm_project_exists
  displayName: Project Exists
  type: boolean
  default: true
- name: parm_project_name
  displayName: Project Name
  type: string
- name: parm_project_prefix
  displayName: Project Prefix (Si no se indica se utilizara el Project Name)
  type: string
  default: ' '
- name: parm_create_module_repositorio_base
  displayName: Create Repositorio Base
  type: boolean
  default: false
- name: parm_default_pools_exists
  displayName: Default Pools Exists
  type: boolean
  default: true
- name: parm_create_IaC_pools
  displayName: Create IaC Pools
  type: boolean
  default: false
- name: parm_create_IaC_variables
  displayName: Create IaC Variables
  type: boolean
  default: false
- name: parm_create_project_groups
  displayName: Create Project Groups (CREATE - Agrega nuevo grupo de usuarios, UPDATE - actualiza grupo de usuarios existentes, NONE - No realiza ningún cambio sobre grupo de usuarios)
  type: string
  default: UPDATE
  values:
  - CREATE
  - UPDATE
  - NONE
- name: parm_update_groups_membership_mode
  displayName: Update existing Groups Membership mode (ADD - Agrega nuevos usuarios al grupo manteniendo los existentes, OVERWRITE - agrega los nuevos usuarios y borra los existentes)
  type: string
  default: ADD
  values:
  - ADD
  - OVERWRITE
- name: parm_asign_project_repos_permissions
  displayName: Create Project Repos Permissions
  type: boolean
  default: false
- name: parm_asign_project_repos_policies
  displayName: Create Project Repos Policies
  type: boolean
  default: false
- name: parm_create_module_monolitos
  displayName: Create Repos Monolitos
  type: boolean
  default: false
- name: parm_repos_monolitos
  displayName: Repositories Molitos 1 por linea, como se muestra. *En caso de que no se haya marcado la opción anterior no se crearan aunque se indiquen los nombres.
  type: object
  default:
    - APP
    - DATABASE
    - WEBSERVICE
- name: parm_create_module_gitops
  displayName: Create Modulo GITOPS
  type: boolean
  default: false
- name: parm_create_module_microservicios
  displayName: Create Module Microservicios
  type: boolean
  default: false
- name: parm_repos_microservicios
  displayName: Repositories Microservicios 1 por linea, como se muestra. *En caso de que no se haya marcado la opción anterior no se crearan aunque se indiquen los nombres.
  type: object
  default:
      - MS_1
      - MS_2
      - MS_3
- name: parm_create_module_cloud_dev
  displayName: Create Modulo Cloud-Dev
  type: boolean
  default: false
- name: parm_create_module_cloud_prod
  displayName: Create Modulo Cloud-Prod
  type: boolean
  default: false
- name: parm_create_module_ansible_base_repos
  displayName: Create Module Ansible Base Repos
  type: boolean
  default: false
- name: parm_repos_ansible
  displayName: Repositories proyectos Ansible 1 por linea, como se muestra. *En caso de que no se haya marcado la opción anterior no se crearan aunque se indiquen los nombres.
  type: object
  default:
      - MS_1
      - MS_2
      - MS_3  
- name: parm_user_group_lt
  displayName: Usuarios aprobadores grupo LT 1 por linea, como se muestra. *Tienen que ser usuario validos para no presentar error
  type: object
  default:
      - user1@baccredomatic.cr
      - user2@baccredomatic.cr
- name: parm_user_group_po
  displayName: Usuarios aprobadores grupo PO 1 por linea, como se muestra. *Tienen que ser usuario validos para no presentar error
  type: object
  default:
      - user1@baccredomatic.cr
      - user2@baccredomatic.cr
- name: parm_user_group_developers
  displayName: Usuarios grupo Developers
  type: object
  default:
      - user1@baccredomatic.cr
      - user2@baccredomatic.cr

resources:
  repositories: 
  - repository: DevOpsPsScripts
    type: git
    name: DEVOPS/DEVOPS-PS-SCRIPTS
    ref: 'refs/heads/master'
    endpoint: 'AzureDevOpsPaaS'
  - repository: ExternalTemplates
    type: git
    name: DEVOPS/AZURE-DEVOPS-TEMPLATES
    ref: 'refs/heads/master'
    endpoint: 'AzureDevOpsPaaS'    

variables:
- template: '../templates/defaultMaintenanceProjectVariables.yml'
- group: ANSIBLE-KEYS
- name: project_exists
  value: ${{ lower(parameters.parm_project_exists) }}
- name: create_project_groups
  value: ${{ lower(eq(parameters.parm_create_project_groups,'CREATE')) }}
- name: update_groups_membership
  value: ${{ lower(eq(parameters.parm_create_project_groups,'UPDATE')) }}
- name: update_groups_membership_mode
  value: ${{ lower(parameters.parm_update_groups_membership_mode  ) }}
- name: create_module_repositorio_base
  value: ${{ lower(parameters.parm_create_module_repositorio_base) }}
- name: default_pools_exists
  value: ${{ lower(parameters.parm_default_pools_exists) }}
- name: create_IaC_pools
  value: ${{ lower(parameters.parm_create_IaC_pools) }}
- name: create_IaC_variables
  value: ${{ lower(parameters.parm_create_IaC_variables) }}
- name: asign_project_repos_permissions
  value: ${{ lower(parameters.parm_asign_project_repos_permissions) }}
- name: asign_project_repos_policies
  value: ${{ lower(parameters.parm_asign_project_repos_policies) }}
- name: user
  value: ${{ upper(parameters.parm_user) }}
- name: project_name
  value: ${{ upper(parameters.parm_project_name) }}
- name: project_description
  value: ' '
- name: project_prefix
  value: ${{ upper(parameters.parm_project_prefix) }}
- name: create_module_monolitos
  value: ${{ lower(parameters.parm_create_module_monolitos) }}
- name: repos_monolitos
  value: ${{ convertToJson(parameters.parm_repos_monolitos) }}
- name: create_module_microservicios
  value: ${{ lower(parameters.parm_create_module_microservicios) }}
- name: create_module_gitops
  value: ${{ lower(parameters.parm_create_module_gitops) }}
- name: repos_microservicios
  value: ${{ convertToJson(parameters.parm_repos_microservicios) }}
- name: create_module_cloud_dev
  value: ${{ lower(parameters.parm_create_module_cloud_dev) }}
- name: create_module_cloud_prod
  value: false
- name: create_module_sql_db_dev
  value: ${{ lower(parameters.parm_create_module_cloud_prod) }}
- name: create_module_sql_db_prod
  value: false
- ${{if parameters.parm_user_group_lt }}:
  - name: users_lt
    value: ${{ convertToJson(parameters.parm_user_group_lt) }}
- ${{if parameters.parm_user_group_po }}:
  - name: users_po
    value: ${{ convertToJson(parameters.parm_user_group_po) }}
- ${{if parameters.parm_user_group_developers }}:
  - name: users_developers
    value: ${{ convertToJson(parameters.parm_user_group_developers) }}
- name: create_module_ansible_base_repos
  value: ${{ lower(parameters.parm_create_module_ansible_base_repos) }}
- name: repos_ansible
  value: ${{ convertToJson(parameters.parm_repos_ansible) }}  

stages: 
- template: '../templates/templateTerraformDevOpsStages.yaml'
    






